# https://fly.io/docs/reference/configuration/
app = 'receipt-processor'
primary_region = 'iad'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
